### ISSUE TITLE
Additional Help

### ISSUE THREAD

**Issue by jahsavage** [onepointsixtwo/dagger_viewmodel#1]
Hi
I'm trying to use your library but I don't understand how ViewModelModule gets bound into the general Dagger components?

Regards
Paul Savage

**Comment by onepointsixtwo** [comment]
Hi Paul

Really sorry for the super-slow reply. I had notifications turned off from GitHub it seems and I've had a busy month or two of work, so I haven't been logging in regularly!

So when you create your general dagger components, you want to add the ViewModelModule into the array of modules which the component is created with. That is, (and in this code example, I've assumed your component is a singleton too simply because that's the pattern I'd normally use):

```
@Singleton
@Component(modules= {ViewModelModule.class, MyOtherModule.class}
public interface MyComponent {
}
```

The above example is in Kotlin rather than Java, but it'd be largely similar in either.

Does this make sense and answer your question, or have I mis-understood the issue you're facing?

Best Regards

John
